# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# syntax=docker/dockerfile:1
FROM python:3.10-slim

# Set working directory
WORKDIR /app

# Install runtime dependencies
RUN pip install --no-cache-dir python-dotenv==1.0.1 httpx==0.28.1 "mcp[cli]==1.5.0"

# Copy application code
COPY main.py .

# Use STDIO transport by default for MCP
ENTRYPOINT ["python", "main.py"]
